name: real_estate_app
description: "Flutter Engineer Translation Test. A real estate mobile app by John Wogu"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.6.1
  go_router: ^14.3.0
  countup: ^0.1.4
  visibility_detector: ^0.4.0+2
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

flutter_launcher_icons:
  image_path: "assets/app-icon.png"
  android: true
  ios: true
